# $Id: Makefile,v 1.1.2.1 2008-03-22 04:49:12 xinwei.niu Exp $
CC=gcc
STRIP=strip
BIN=realpath

all: $(BIN)
	$(STRIP) $^

%.o: %.c
	$(CC) -I. $(CFLAGS) $(EXTRA_CFLAGS) -c -o $@ $^

$(BIN): realpath.o
	$(CC) -o $@ $(EXTRA_LDFLAGS) $(LDFLAGS) $^

clean:
	rm -f *.o $(BIN)
