#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 
	done
}


if [ "$1" = "S" ]; then
	echo 1 > /tmp/boot_status
	run_scripts "$1" "$2"
	rm -rf /tmp/boot_status
else
	run_scripts "$1" "$2"
fi
