#!/bin/sh

# Copyright (C) 2006 OpenWrt.org

case "$ACTION" in
	add)
		[ -n "${PHYSDEVPATH}" ] && {
			/sbin/usb-storage
		}
		;;
	remove)
		[ -n "${PHYSDEVPATH}" ] && {
			/sbin/usb-storage-remove
		}
		;;
esac	
		
