#!/bin/sh
##
## Compatability scripts for older versions
##

## Kill 'icm' if it is alive
ICM_TMP_FILE=/tmp/icm.tmp

ps -ef > ${ICM_TMP_FILE}
if grep -q icm ${ICM_TMP_FILE}; then
    killall icm
fi
rm ${ICM_TMP_FILE}

if eval "type ledcontrol" 2>/dev/null >/dev/null; then
	/sbin/ledcontrol -n wps -c green -s off
elif [ -e /proc/simple_config/tricolor_led ]; then
	echo 0 > /proc/simple_config/tricolor_led
elif [ -e /proc/simple_config/simple_config_led ]; then
	echo 1 > /proc/simple_config/simple_config_led
fi
[ -f /tmp/wps_process_state ] && echo "" > /tmp/wps_process_state
KER_VER_31=`set | uname -a | grep -c "2.6.31"`
if [ "${KER_VER_31}" = 1 ]; then
    pktlogconf -d
fi


killVAP all
#Finally, unload all modules
sleep 1
if [ "${AP_CONF_ACFG}"  -eq "1" ]; then
    prepareACFG unload
fi
/etc/rc.d/rc.wlan down
rm -f /tmp/.apup
